version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - langchain-api

  langchain-api:
    build: ./langchain-api
    ports:
      - "8000:8000"
